### ISSUE TITLE
Setting log_bins does not actually return log bins - cylindrical power spectrum

### ISSUE THREAD

**Issue by DanielaBreitman** [steven-murray/powerbox#29]
Steps to reproduce:
Take a lightcone and calculate the cylindrical power spectrum using:
```
PS_2D, kperp, var_2D, kpar = pb.get_power(lightcones[0],
                                          300.,
                                          res_ndim = 2,
                                          get_variance = True,
                                          bin_ave = True,
                                          log_bins = True,
                                          dimensionless = False
                                          )
```
Then check the bin spacing using: 

```
plt.scatter(np.log10(kperp), np.arange(len(kperp)))
plt.xscale('log')
plt.show()

```
Output plot:
![Output plot](https://github.com/steven-murray/powerbox/assets/39098176/d8968734-3336-4ee3-94e8-9c02f4c96893)

Correct behaviour when adding `bins = 10**np.logspace(nyq, -0.34, nbins+1)` in `get_power`: ![Output plot](https://github.com/steven-murray/powerbox/assets/39098176/4457c9ce-4db5-4e7c-847f-daca61b9232b)

**Comment by DanielaBreitman** [comment]
@steven-murray  I can fix this, by the way. I put the issue just to track.

**Comment by steven-murray** [comment]
@DanielaBreitman which line of code do you think is in error here?

**Comment by DanielaBreitman** [comment]
The issue must be [here](https://github.com/steven-murray/powerbox/blob/master/src/powerbox/tools.py#L19C20-L19C20). Since the `bins` argument takes the input bins directly (second plot), then the issue must be that there should be a `10**` on line 19 in `tools.py`. (I did not test this btw. I can test and add an update).

**Comment by DanielaBreitman** [comment]
Also, another thing is that the kpar bins are not in log either (i.e. I would expect `log_bins = True` to apply to both `kperp` and `kpar`, but this I don't know how to fix.

**Comment by steven-murray** [comment]
I don't think that is correct, see https://numpy.org/doc/stable/reference/generated/numpy.logspace.html. `logspace` already returns values in linear space, eg. `np.logspace(2, 3, 2) == [100, 1000]`

**Comment by DanielaBreitman** [comment]
Ah you're right. `kperp` is fine then. My bad. `kpar` however is not in log-space like `kperp`. Is this intended behaviour?

**Comment by DanielaBreitman** [comment]
I'll close this then.

**Comment by steven-murray** [comment]
Yes, so the non-averaged dimensions of the power will never be log (they are just FT'd). We could certainly look at binning them in log-bins as well, but you could also think about doing that to the result yourself?

**Comment by DanielaBreitman** [comment]
Doing it myself is ok. It's just that it should say in the description of `log_bins` that it only applies to the averaged dimensions.
