### ISSUE TITLE
Errot with get_power

### ISSUE THREAD

**Issue by PabloVD** [steven-murray/powerbox#5]
I tried to compute the cross-correlated power spectrum of two fields using get_power, including as an argument another field deltax2. I obtained an error message, even if deltax2 was the same than deltax1 (which should give the standard power spectrum). I noticed that there is an error in tools.py/get_power, line 463, which reads:

    if deltax2 is not None and deltax.shape != len(deltax2.shape):

but it should be:

    if deltax2 is not None and deltax.shape != deltax2.shape:

which works without problem. I checked it recovering the power spectrum when deltax2=deltax1.

**Comment by steven-murray** [comment]
Thanks @PabloVD. This should be fixed in v0.6.1 up on pypi now.
